name: Build
on:
  push:
    branches:
      - master
      - ci
      - 'ci-*'
    tags:
      - 'v*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build (Go ${{ matrix.go-version }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - go-version: '1.18'
            allow-release: true
        go-version:
          - '1.19'
        allow-upload:
          - true
        allow-release:
          - false
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: ./setup.sh
      - name: Build
        env:
          build_js: 1
        run: ./build.sh
      - name: Build tools
        run: ./tools/build.sh
      - name: Test
        run: go test ./...
      - name: Package
        id: release
        if: ${{ matrix.allow-upload }}
        run: |
          ./release.sh | tee release.log
          version="$(grep Version: release.log | sed 's/Version:\s*//')"
          suffix=
          if [[ "${{ matrix.allow-release }}" != "true" ]]; then
            suffix="-${{ matrix.go-version }}"
          fi
          echo "::set-output name=version::$version"
          echo "::set-output name=output_prefix::bin/release/$version/TBA-uploader-$version$suffix"
      - name: Upload artifact (win32)
        if: ${{ matrix.allow-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: TBA-uploader-${{steps.release.outputs.version}}-win32.zip
          path: ${{steps.release.outputs.output_prefix}}-win32.zip
      - name: Upload artifact (win64)
        if: ${{ matrix.allow-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: TBA-uploader-${{steps.release.outputs.version}}-win64.zip
          path: ${{steps.release.outputs.output_prefix}}-win64.zip
      - name: Upload artifact (mac64)
        if: ${{ matrix.allow-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: TBA-uploader-${{steps.release.outputs.version}}-mac64.zip
          path: ${{steps.release.outputs.output_prefix}}-mac64.zip
      - name: Upload artifact (linux64)
        if: ${{ matrix.allow-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: TBA-uploader-${{steps.release.outputs.version}}-linux64.zip
          path: ${{steps.release.outputs.output_prefix}}-linux64.zip
      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.allow-release && startsWith(github.ref, 'refs/tags/v') }}
        with:
          files: |
            ${{steps.release.outputs.output_prefix}}-*.zip
