name: Build
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build (Go ${{ matrix.go-version }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - go-version: '1.20'
            allow-upload: true
            allow-release: true
        go-version:
          - '1.18'
        allow-upload:
          - true
        allow-release:
          - false
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: ./setup.sh
      - name: Build
        env:
          build_js: 1
        run: ./build.sh
      - name: Build tools
        run: ./tools/build.sh
      - name: Test
        run: go test ./...
      - name: Package
        id: release
        if: ${{ matrix.allow-upload }}
        run: |
          ./release.sh | tee release.log
          version="$(grep Version: release.log | sed 's/Version:\s*//')"
          suffix=
          if [[ "${{ matrix.allow-release }}" != "true" ]]; then
            suffix="-go${{ matrix.go-version }}"
          fi
          echo "version=$version$suffix" >> "$GITHUB_OUTPUT"
          echo "output_prefix=bin/release/$version/TBA-uploader-$version" >> "$GITHUB_OUTPUT"
      - name: Upload artifact (windows-x86_64)
        if: ${{ matrix.allow-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: TBA-uploader-${{steps.release.outputs.version}}-windows-x86_64.zip
          path: ${{steps.release.outputs.output_prefix}}-windows-x86_64.zip
      - name: Upload artifact (mac-x86_64)
        if: ${{ matrix.allow-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: TBA-uploader-${{steps.release.outputs.version}}-mac-x86_64.zip
          path: ${{steps.release.outputs.output_prefix}}-mac-x86_64.zip
      - name: Upload artifact (mac-arm64)
        if: ${{ matrix.allow-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: TBA-uploader-${{steps.release.outputs.version}}-mac-arm64.zip
          path: ${{steps.release.outputs.output_prefix}}-mac-arm64.zip
      - name: Upload artifact (linux-x86_64)
        if: ${{ matrix.allow-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: TBA-uploader-${{steps.release.outputs.version}}-linux-x86_64.zip
          path: ${{steps.release.outputs.output_prefix}}-linux-x86_64.zip
      - name: Upload artifact (linux-arm64)
        if: ${{ matrix.allow-upload }}
        uses: actions/upload-artifact@v3
        with:
          name: TBA-uploader-${{steps.release.outputs.version}}-linux-arm64.zip
          path: ${{steps.release.outputs.output_prefix}}-linux-arm64.zip
      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.allow-release && startsWith(github.ref, 'refs/tags/v') }}
        with:
          files: |
            ${{steps.release.outputs.output_prefix}}-*.zip
